import { Suspense } from 'react';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import type { Task } from '@/types';

import { AddTask } from '@/app/components/AddTask';
import { TodoList } from '@/app/components/TodoList';

import { getAllTasks } from '@/app/api';

import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Todo App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const tasks: Task[] = await getAllTasks();

  return (
    <html lang="ja">
      <body className={inter.className}>
        <main className="flex min-h-screen flex-col items-center justify-center bg-slate-100 py-5">
          <h1 className="text-4xl font-bold text-gray-500">Todo App</h1>
          <div className="mx-3 mt-5 w-full max-w-3xl bg-white px-7 py-5 shadow-md">
            <AddTask />
            <Suspense fallback={<div>Loading...</div>}>
              <TodoList tasks={tasks} />
            </Suspense>
          </div>
        </main>
        {children}
      </body>
    </html>
  );
}
